all:
  hosts:
    alex_machine:  # Un alias pour votre machine
      ansible_host: 172.29.241.4
      ansible_port: 2222               # Port SSH de la machine distante
      ansible_user: alex               # Utilisateur SSH
      ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Clé privée pour SSH
      ansible_become: yes              # Utilisation de sudo
      ansible_become_method: sudo      # Méthode pour sudo
      ansible_become_pass: ""          # Vide si sudo ne demande pas de mot de passe
