all:
  hosts:
    alex_machine:  # Un alias pour la machine distante
      ansible_host: 172.29.241.4
      ansible_port: 2222
      ansible_user: alex
      ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Clé SSH utilisée par Jenkins
      ansible_become: yes
