
- name: Install and configure Nginx
  hosts: all
  become: yes  # Exige sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
